export const SET_HE_THONG_RAP_CHIEU = "SET_HE_THONG_RAP_CHIEU";
export const SET_CHI_TIET_PHIM = "SET_CHI_TIET_PHIM";
export const SET_DANH_SACH_HE_THONG_RAP = "SET_DANH_SACH_HE_THONG_RAP";
export const SET_DANH_SACH_HE_THONG_CUM_RAP = "SET_DANH_SACH_HE_THONG_CUM_RAP";
